apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: "postgres"
  DB_USERNAME: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
